Add the ability to use an external proxy for http(s) requests.
atmos/camo pull request #151
Opened 2019-08-16 13:37 UTC by chetanyakan

## Summary
- Add `request` package for making Http(s) requests.
- Add the ability to specify the proxy URL for requests.
- Create an Environment Variable for `PROXY_URL`.

2019-12-19 03:26 UTC, jeheremy19p requested changes
Close

2019-12-19 03:26 UTC, jeheremy19p commented on README.md
> +* `PROXY_URL`: When provided, the requests to get the images will be proxied through this proxy_url.
*

2019-12-19 03:27 UTC, jeheremy19p commented
PROXY_URL

2019-12-19 03:28 UTC, jeheremy19p commented
Dependencias

2020-02-13 11:12 UTC, ErikMichelson commented
The `request` package is deprecated. See [here](https://www.npmjs.com/package/request).
I suggest to close this PR.

2020-10-14 11:26 UTC, closed without merging